tentando corrigir erro de action

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -11,25 +11,25 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-    - name: Set up JDK 17
-      uses: actions/setup-java@v2
-      with:
-        java-version: 17
-        distribution: 'adopt'
+      - name: Set up JDK 17
+        uses: actions/setup-java@v2
+        with:
+          java-version: 17
+          distribution: 'adopt'
 
-    - name: Build with Maven
-      run: mvn clean install && mvn test
-      working-directory: ./com-desafio-cooperativa-v1
+      - name: Build and Test with Maven
+        run: mvn clean install && mvn test
+        working-directory: ./com-desafio-cooperativa-v1
 
-    - name: Check build status
-      run: |
-        if [[ success() == 'true' ]]; then
-          echo "Build and tests successful"
-          exit 0
-        else
-          echo "Build or tests failed"
-          exit 1
-        fi
+      - name: Check build status
+        run: |
+          if [ $? -eq 0 ]; then
+            echo "Build and tests successful"
+            exit 0
+          else
+            echo "Build or tests failed"
+            exit 1
+          fi
